import { Request, Response, NextFunction } from 'express';


// FunciÃ³n para manejar errores en controladores async
export const catchedAsync = (fn: (req: Request, res: Response, next: NextFunction) => Promise<any>) => { 
    return (req: Request, res: Response, next: NextFunction) => { 
        fn(req, res, next).catch((error) => next(error)); // ğŸ”¥ Asegurarse de pasar `next`
    }
};
